# Generated by Django 4.2.3 on 2023-08-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('clasificacion', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='ciclista',
            old_name='pais',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='ciclista',
            old_name='podios',
            new_name='edad',
        ),
        migrations.RemoveField(
            model_name='ciclista',
            name='team',
        ),
        migrations.RemoveField(
            model_name='ciclista',
            name='victorias',
        ),
        migrations.DeleteModel(
            name='Clasificacion',
        ),
    ]
